spring.application.name=inventory-service
server.port=${PORT:8081}

spring.datasource.url=${SMARTLOGIX_DB_URL:jdbc:postgresql://localhost:5432/smartlogix_inventory}
spring.datasource.username=${SMARTLOGIX_DB_USERNAME:smartlogix}
spring.datasource.password=${SMARTLOGIX_DB_PASSWORD:smartlogix123}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.sql.init.mode=always

management.endpoints.web.exposure.include=health,info

security.jwt.secret=${SMARTLOGIX_JWT_SECRET:smartlogix-development-secret-key-change-me-2026}

smartlogix.tenancy.allowed-tenants=${SMARTLOGIX_ALLOWED_TENANTS:empresa1,empresa2}
smartlogix.tenancy.default-tenant=${SMARTLOGIX_DEFAULT_TENANT:empresa1}
