package smartlogix.inventory_service.tenant;

import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class TenantSchemaInitializer implements ApplicationRunner {

    private final JdbcTemplate jdbcTemplate;
    private final TenantProperties tenantProperties;

    public TenantSchemaInitializer(JdbcTemplate jdbcTemplate, TenantProperties tenantProperties) {
        this.jdbcTemplate = jdbcTemplate;
        this.tenantProperties = tenantProperties;
    }

    @Override
    public void run(ApplicationArguments args) {
        tenantProperties.getAllowedTenants()
                .forEach(this::initializeTenantSchema);
    }

    private void initializeTenantSchema(String tenant) {
        jdbcTemplate.execute("CREATE SCHEMA IF NOT EXISTS " + tenant);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS %s.products (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    sku VARCHAR(80) NOT NULL,
                    name VARCHAR(160) NOT NULL,
                    description VARCHAR(500),
                    category VARCHAR(100) NOT NULL,
                    unit_price NUMERIC(12, 2) NOT NULL,
                    stock INTEGER NOT NULL,
                    active BOOLEAN NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    CONSTRAINT uk_products_sku UNIQUE (sku)
                )
                """.formatted(tenant));
    }
}
